In [1]:
import pandas as pd

In [2]:
# orderlines_cl.csv
url = "https://drive.google.com/file/d/1OhtkQS2fwOYdzfd-qPh7im35iLc-L9TA/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orderlines_cl = pd.read_csv(path)

In [3]:
df = orderlines_cl.copy()

In [ ]:
df.columns

Index(['id', 'id_order', 'product_id', 'product_quantity', 'sku', 'unit_price',
       'date'],
      dtype='object')

In [ ]:
df.head()

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38

Calculate the total sales (revenue) for each sku:

In [ ]:
# Assuming your DataFrame is named 'df'
total_sales_per_sku = df.groupby('sku')['unit_price'].sum().reset_index()
print(total_sales_per_sku)

            sku  unit_price
0     8MO0001-A       25.92
1     8MO0003-A       38.55
2       8MO0007      619.71
3       8MO0008      651.70
4       8MO0009      499.60
...         ...         ...
6793    ZAG0041       39.98
6794    ZAG0042       19.99
6795    ZEP0007      685.59
6796    ZEP0008      104.12
6797    par0072     2689.90

[6798 rows x 2 columns]

Find the average unit price and total quantity sold for each SKU:

In [ ]:
avg_unit_price_and_quantity_per_sku = df.groupby('sku').agg({'unit_price': 'mean', 'product_quantity': 'sum'}).reset_index()
print(avg_unit_price_and_quantity_per_sku)

            sku  unit_price  product_quantity
0     8MO0001-A   12.960000                 2
1     8MO0003-A   12.850000                 3
2       8MO0007   21.369310                30
3       8MO0008   21.723333                31
4       8MO0009   17.842857                30
...         ...         ...               ...
6793    ZAG0041   19.990000                 2
6794    ZAG0042   19.990000                 1
6795    ZEP0007  137.118000                 5
6796    ZEP0008  104.120000                 1
6797    par0072  224.158333                13

[6798 rows x 3 columns]

Find the date on which the maximum revenue was generated:

In [ ]:
max_revenue_date = df.groupby('date')['unit_price'].sum().idxmax()
print(max_revenue_date)

2017-01-20 12:00:01

Calculate the total revenue generated on each date:

In [ ]:
revenue_per_date = df.groupby('date')['unit_price'].sum().reset_index().sort_values('date', ascending=False)
print(revenue_per_date)

                       date  unit_price
207365  2018-03-14 13:58:36       13.99
207364  2018-03-14 13:58:01       19.99
207363  2018-03-14 13:57:41        9.99
207362  2018-03-14 13:57:34      141.58
207361  2018-03-14 13:57:25       42.99
...                     ...         ...
4       2017-01-01 01:06:38       23.74
3       2017-01-01 00:51:40       68.39
2       2017-01-01 00:20:57      474.05
1       2017-01-01 00:19:45      399.00
0       2017-01-01 00:07:19       18.99

[207366 rows x 2 columns]

Find the top 5 sku with the highest revenue:

In [ ]:
top_5_products = df.groupby('sku')['unit_price'].sum().nlargest(5).reset_index()
print(top_5_products)

       sku  unit_price
0  APP2485   734093.81
1  APP2477   560846.88
2  APP2483   521304.78
3  APP2072   471162.93
4  APP1970   365511.21

Calculate the average unit price for each ID and sku combination and sort by sku:

In [ ]:
avg_unit_price_per_id_product = df.groupby(['id', 'sku'])['unit_price'].mean().reset_index().sort_values('sku')
print(avg_unit_price_per_id_product)

             id        sku  unit_price
107569  1365769  8MO0001-A       12.96
107775  1366184  8MO0001-A       12.96
212757  1640610  8MO0003-A       12.85
205253  1621640  8MO0003-A       12.85
209166  1631017  8MO0003-A       12.85
...         ...        ...         ...
184918  1563699    par0072      209.99
2525    1128367    par0072      199.00
142766  1447414    par0072      197.99
176514  1536762    par0072      220.99
76847   1287779    par0072      269.99

[216250 rows x 3 columns]

Find the date with the highest number of orders:

In [8]:
date_with_max_orders = df.groupby('date')['id_order'].nunique().idxmax()
print(date_with_max_orders)

2017-08-18 12:00:01

Find the product with the highest and lowest unit price:

In [11]:
product_with_highest_unit_price = df.loc[df['unit_price'].idxmax()]
product_with_lowest_unit_price = df.loc[df['unit_price'].idxmin()]
print("Product with the highest unit price:")
print(product_with_highest_unit_price)
print("\nProduct with the lowest unit price:")
print(product_with_lowest_unit_price)

Product with the highest unit price:
id                              1206437
id_order                         335869
product_id                            0
product_quantity                      1
sku                             PAC1428
unit_price                       999.99
date                2017-03-16 16:56:58
Name: 37484, dtype: object

Product with the lowest unit price:
id                              1268645
id_order                         365886
product_id                            0
product_quantity                      1
sku                             APP1465
unit_price                       -119.0
date                2017-06-15 12:48:54
Name: 67619, dtype: object